services:
  # PostgreSQL service
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

  # Redis service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Kafka service
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"

  # # NATS service
  # nats:
  #   image: nats:latest
  #   ports:
  #     - "4222:4222"

  # # ClickHouse service
  # clickhouse:
  #   image: yandex/clickhouse-server:latest
  #   ports:
  #     - "8123:8123"

  # Sidecar service to test connections to each database
  sidecar:
    build:
      context: .
    entrypoint: ["/bin/bash"]
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
      REDIS_HOST: redis
      KAFKA_BROKER: kafka:9092
      ELASTICSEARCH_HOST: elasticsearch
      NATS_HOST: nats
      CLICKHOUSE_HOST: clickhouse

    depends_on:
      - postgres
      - redis
      - kafka
      - elasticsearch
      # - nats
      # - clickhouse
    ports:
      - "8080:8080" # Sidecar service port, if needed for testing

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
